'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {studyRequest,downloadStudy} from './study-request';
import {csvCell} from './export';
import {readableNote,savedSourceLanguage} from './readable-note';
import {displayBookTitle} from './word-display';
import {FormattedText} from '@/components/ui/formatted-text';
type RecordItem={id:string;kind:string;text:string;note:string;location:string;document:{id:string;title:string}};
export default function ReadingRecords(){
 const [items,setItems]=useState<RecordItem[]>([]),[q,setQ]=useState(''),[filter,setFilter]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');void studyRequest<{items:RecordItem[]}>('/api/study?recordsOnly=true',{signal:abort.signal}).then(data=>{if(!abort.signal.aborted)setItems(data.items.filter(i=>i.kind!=='word'));}).catch(error=>{if(!abort.signal.aborted)setError(error instanceof Error?error.message:'记录加载失败');}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();},[retry]);
 const visible=items.filter(item=>(filter==='all'||item.kind===filter)&&(item.text+' '+readableNote(item.kind,item.note)+' '+item.document.title).toLowerCase().includes(q.toLowerCase()));
 async function remove(item:RecordItem){if(!window.confirm('删除这条阅读记录？'))return;setBusy(item.id);try{await studyRequest('/api/study?entryId='+encodeURIComponent(item.id),{method:'DELETE'});setItems(list=>list.filter(i=>i.id!==item.id));}catch(error){setError(error instanceof Error?error.message:'删除失败');}finally{setBusy('');}}
 function download(format:'csv'|'md'){const text=format==='csv'?'\uFEFF'+[['类型','原文','记录','书籍','位置'],...visible.map(item=>[item.kind,item.text,readableNote(item.kind,item.note),item.document.title,item.location])].map(row=>row.map(csvCell).join(',')).join('\r\n'):visible.map(item=>'## '+displayBookTitle(item.document.title)+'\n\n'+item.text+'\n\n'+readableNote(item.kind,item.note)+'\n\n位置：'+item.location).join('\n\n---\n\n');downloadStudy(text,'reading-records.'+format,format==='csv'?'text/csv;charset=utf-8':'text/markdown;charset=utf-8');}
 return <section aria-label="阅读记录"><h2 className="mt-5 text-xl font-semibold">阅读记录</h2><div className="my-5 flex flex-wrap gap-2"><input aria-label="搜索阅读记录" className="native-field min-w-40 flex-1" value={q} placeholder="搜索笔记、书签或对话" onChange={e=>setQ(e.target.value)}/><select aria-label="阅读记录类型" className="native-field w-auto" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">全部记录</option><option value="note">笔记</option><option value="bookmark">书签</option><option value="chat">AI 对话</option></select><button className="native-action" disabled={!visible.length} onClick={()=>download('md')}>导出 Markdown</button><button className="native-action" disabled={!visible.length} onClick={()=>download('csv')}>导出 CSV</button></div>{error&&<p role="alert" className="text-sm text-destructive">{error}<button className="ml-3 underline" onClick={()=>setRetry(v=>v+1)}>重试</button></p>}{loading?<p role="status">正在加载阅读记录…</p>:!visible.length?<p className="py-10 text-sm text-muted-foreground">暂无匹配的记录。</p>:visible.map(item=><article key={item.id} className="space-y-3 border-b border-border py-6"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-medium">《{displayBookTitle(item.document.title)}》 · {item.kind==='note'?'笔记':item.kind==='bookmark'?'书签':'AI 对话'}</h3><details className="relative"><summary aria-label="更多记录操作" className="cursor-pointer list-none px-3">⋯</summary><button className="absolute right-0 z-10 whitespace-nowrap rounded-lg border bg-popover p-3 text-sm text-destructive" disabled={busy===item.id} onClick={()=>void remove(item)}>删除记录</button></details></div><p className="line-clamp-3 whitespace-pre-wrap text-sm leading-6">{item.text}</p><details><summary className="cursor-pointer text-xs text-muted-foreground">查看记录</summary><div className="mt-3"><FormattedText text={readableNote(item.kind,item.note)||'暂无补充内容。'}/></div></details><Link className="text-xs text-primary hover:underline" href={'/reader/'+encodeURIComponent(item.document.id)+'?sourceLanguage='+savedSourceLanguage(item.note)+'&location='+encodeURIComponent(item.location)}>返回原文</Link></article>)}</section>;
}
