'use client';
import {useEffect,useState} from 'react';
import type {SourceLanguage} from '@/server/vocabulary/types';
import type {DictionarySenseCandidate} from '@/server/vocabulary/senses';
import {studyRequest} from './study-request';
type SenseInfo={revision:number;selectedDictionarySenseId:string|null;candidates:DictionarySenseCandidate[];changes:Array<{id:string;action:string;createdAt:string}>};
export default function SenseControls({id,word,sourceLanguage,revision,sources,onChanged,disabled=false}:{id:string;word:string;sourceLanguage:SourceLanguage;revision:number;sources:Array<{id:string;bookTitle:string;sentence:string}>;onChanged:(targetId:string)=>void;disabled?:boolean}){
 const [open,setOpen]=useState(false),[info,setInfo]=useState<SenseInfo|null>(null),[others,setOthers]=useState<Array<{id:string;word:string;contextMeaning:string}>>([]),[candidate,setCandidate]=useState(''),[target,setTarget]=useState(''),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{if(!open)return;const abort=new AbortController();setError('');void Promise.all([studyRequest<SenseInfo>('/api/study/vocabulary/senses?senseId='+encodeURIComponent(id),{signal:abort.signal}),studyRequest<{items:Array<{id:string;word:string;sourceLanguage:string;contextMeaning:string}>}>('/api/study/vocabulary?'+new URLSearchParams({q:word,sourceLanguage,limit:'100'}),{signal:abort.signal})]).then(([value,list])=>{if(!abort.signal.aborted){setInfo(value);setCandidate(value.selectedDictionarySenseId??'');setOthers(list.items.filter(t=>t.id!==id&&t.word===word&&t.sourceLanguage===sourceLanguage));}}).catch(error=>{if(!abort.signal.aborted)setError(error instanceof Error?error.message:'义项加载失败');});return()=>abort.abort();},[open,id,word,sourceLanguage,revision,refresh]);
 async function perform(action:'confirm'|'merge'|'split'){
  const message=action==='merge'?'确认合并到选中义项？保留目标的复习排程、全部出处和历史；人工修改冲突时会提示。':action==='split'?'确认把勾选出处拆成新的学习义项？原有复习历史保留，新义项从空卡开始。':'确认这个词在当前语境中的词典义项？匹配的同义收藏可能归并，人工释义不会被替换。';
  if(disabled||!window.confirm(message))return;setBusy(true);setError('');try{const body=action==='confirm'?{action,senseId:id,dictionarySenseId:candidate,revision:info?.revision??revision}:action==='merge'?{action,sourceIds:[id],targetId:target}:{action,senseId:id,encounterIds:selected};const result=await studyRequest<{targetId:string}>('/api/study/vocabulary/senses',{method:'POST',body:JSON.stringify(body)});onChanged(result.targetId);}catch(error){setError(error instanceof Error?error.message:'义项更新失败');}finally{setBusy(false);}
 }
 return <details className="border-t border-border pt-4" onToggle={event=>setOpen(event.currentTarget.open)}><summary className="cursor-pointer text-sm text-muted-foreground">义项确认、合并与拆分</summary><div className="mt-4 space-y-5 text-sm">{disabled&&<p className="text-xs text-muted-foreground">先保存或取消正在编辑的释义，再调整义项。</p>}{error&&<p role="alert" className="text-xs text-destructive">{error}<button className="ml-2 underline" onClick={()=>setRefresh(v=>v+1)}>刷新</button></p>}{info?<><section className="space-y-2"><label className="block text-xs text-muted-foreground">确认词典义项<select aria-label="确认词典义项" value={candidate} disabled={busy||disabled} className="native-field mt-2" onChange={e=>setCandidate(e.target.value)}><option value="">保留待确认状态</option>{info.candidates.map(c=><option key={c.id} value={c.id}>{c.pos} · {c.definition.slice(0,180)}</option>)}</select></label><button className="native-action" disabled={busy||disabled||!candidate} onClick={()=>void perform('confirm')}>确认当前义项</button>{!info.candidates.length&&<p className="text-xs text-muted-foreground">离线词典暂无可确认的义项，现有收藏仍保留。</p>}</section><section className="space-y-2"><label className="block text-xs text-muted-foreground">同词的其他收藏<select aria-label="合并到哪个义项" className="native-field mt-2" value={target} disabled={busy||disabled} onChange={e=>setTarget(e.target.value)}><option value="">选择保留的义项</option>{others.map(t=><option key={t.id} value={t.id}>{t.contextMeaning||'待整理义项'}</option>)}</select></label><button className="native-action" disabled={busy||disabled||!target} onClick={()=>void perform('merge')}>合并到选中义项</button></section><section><p className="mb-2 text-xs text-muted-foreground">勾选需要另立义项的出处</p>{sources.map(source=><label key={source.id} className="mb-3 flex items-start gap-2 text-xs leading-6"><input type="checkbox" disabled={busy||disabled} checked={selected.includes(source.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,source.id]:old.filter(id=>id!==source.id))} className="mt-1.5 accent-primary"/><span>《{source.bookTitle}》<br/>{source.sentence}</span></label>)}<button className="native-action" disabled={busy||disabled||!selected.length} onClick={()=>void perform('split')}>拆分勾选出处</button></section><details><summary className="cursor-pointer text-xs text-muted-foreground">义项调整记录 · {info.changes.length}</summary>{info.changes.map(change=><p key={change.id} className="mt-2 text-xs text-muted-foreground">{{merge:'合并',split:'拆分',confirm:'人工确认'}[change.action]??change.action} · {new Date(change.createdAt).toLocaleDateString()}</p>)}</details></>:!error&&<p role="status" className="text-xs text-muted-foreground">正在加载义项…</p>}</div></details>;
}
