// @vitest-environment jsdom
import {createElement} from 'react';
import {cleanup,fireEvent,render,screen} from '@testing-library/react';
import {afterEach,expect,it,vi} from 'vitest';
import {ReaderEdgeNavigation} from '@/components/reader/reader-edge-navigation';
import {epubReaderGutter,compactEpubCss,installCompactEpubPresentation} from '@/components/reader/epub-reader-presentation';
afterEach(()=>{cleanup();vi.restoreAllMocks();window.getSelection()?.removeAllRanges();});
function pointer(target:Element,type:string,extra:Record<string,unknown>={}){const e=new Event(type,{bubbles:true});for(const [k,v] of Object.entries({pointerId:1,pointerType:'mouse',button:0,isPrimary:true,clientX:5,clientY:100,...extra}))Object.defineProperty(e,k,{value:v});fireEvent(target,e);}
const mount=(flow:'paginated'|'vertical'='paginated',ready=true)=>{const turn=vi.fn();render(createElement(ReaderEdgeNavigation,{flow,ready,onTurn:turn,hasSelection:()=>!window.getSelection()?.isCollapsed}));return turn;};
it('has two empty accessible page edges only in pagination, with no visible arrows',()=>{mount();for(const label of ['上一页（点击页边）','下一页（点击页边）']){const edge=screen.getByRole('button',{name:label});expect(edge.textContent).toBe('');expect(edge.style.width).toBe(epubReaderGutter);}cleanup();mount('vertical');expect(screen.queryByRole('button')).toBeNull();});
it('pages only on a short primary press in the blank edge and keeps keyboard activation',()=>{const turn=mount(),edge=screen.getByRole('button',{name:'下一页（点击页边）'});pointer(edge,'pointerdown');pointer(edge,'pointerup');fireEvent.click(edge,{detail:1});expect(turn).toHaveBeenCalledWith(1);fireEvent.click(screen.getByRole('button',{name:'上一页（点击页边）'}),{detail:0});expect(turn).toHaveBeenLastCalledWith(-1);});
it('does not navigate from selection, a drag, long press, cancellation, or a restoring reader',()=>{const turn=mount(),edge=screen.getByRole('button',{name:'下一页（点击页边）'});const p=document.createElement('p');p.textContent='Selected source';document.body.append(p);const r=document.createRange();r.selectNodeContents(p);window.getSelection()!.addRange(r);pointer(edge,'pointerdown');pointer(edge,'pointerup');fireEvent.click(edge,{detail:1});window.getSelection()!.removeAllRanges();p.remove();pointer(edge,'pointerdown');pointer(edge,'pointermove',{clientX:30});pointer(edge,'pointerup',{clientX:30});fireEvent.click(edge,{detail:1});vi.spyOn(Date,'now').mockReturnValueOnce(1000).mockReturnValueOnce(1600);pointer(edge,'pointerdown');pointer(edge,'pointerup');fireEvent.click(edge,{detail:1});pointer(edge,'pointerdown');pointer(edge,'pointercancel');fireEvent.click(edge,{detail:1});expect(turn).not.toHaveBeenCalled();cleanup();const restoring=mount('paginated',false);fireEvent.click(screen.getByRole('button',{name:'下一页（点击页边）'}));expect(restoring).not.toHaveBeenCalled();});
it('styles compact prose without changing headings or desktop justification and tracks outer viewport size',()=>{expect(compactEpubCss).toContain('text-align:start !important');expect(compactEpubCss).toContain('word-spacing:normal !important');expect(compactEpubCss).toContain('padding-inline:20px !important');expect(compactEpubCss).not.toContain('h1');const frame=document.createElement('iframe');document.body.append(frame);const doc=frame.contentDocument!;Object.defineProperty(window,'innerWidth',{value:390,configurable:true});const off=installCompactEpubPresentation(doc,window,'vertical');expect(doc.documentElement.dataset.readerCompact).toBe('true');expect(doc.documentElement.dataset.readerFlow).toBe('vertical');Object.defineProperty(window,'innerWidth',{value:1200,configurable:true});window.dispatchEvent(new Event('resize'));expect(doc.documentElement.dataset.readerCompact).toBe('false');off();Object.defineProperty(window,'innerWidth',{value:390,configurable:true});window.dispatchEvent(new Event('resize'));expect(doc.documentElement.dataset.readerCompact).toBeUndefined();frame.remove();});
