import {afterEach,expect,it,vi} from 'vitest';
import {createSemanticFlipController} from '@/components/reader/semantic-flip-controller';
import {createReaderAIClientBudget} from '@/components/reader/reader-ai-budget';
import type {SemanticFlipInput} from '@/lib/semantic-flip';
import type {Occurrence} from '@/components/reader/source-position';
const domain={documentId:'doc',sourceLanguage:'en' as const,targetLanguage:'zh' as const,aiEpoch:'0'};
const occurrence=(id:string):Occurrence=>({id,position:{kind:'pdf',selectionKey:id,start:3,end:11},word:'occasion',originalRange:{} as Range});
const inputFor=(o:Occurrence)=>({documentId:domain.documentId,sourceLanguage:domain.sourceLanguage,targetLanguage:domain.targetLanguage,sourceText:'An occasion.',start:3,end:11,targetWord:o.word,occurrence:o.id});
const result=(replacement='场合')=>({replacement,provider:'fixture',model:'fixture'});
const flush=async()=>{for(let i=0;i<24;i++)await Promise.resolve();};
const deferred=<T>()=>{let resolve!:(v:T)=>void,reject!:(e:unknown)=>void;const promise=new Promise<T>((yes,no)=>{resolve=yes;reject=no;});return {promise,resolve,reject};};
const setup=()=>{const budget=createReaderAIClientBudget(),request=vi.fn(async(_input:SemanticFlipInput,_signal:AbortSignal)=>result()),apply=vi.fn(async(_o:Occurrence,_replacement:string)=>{}),restore=vi.fn(async(_id:string)=>{}),restoreAll=vi.fn(async()=>{}),changed=vi.fn();const options={domain,budget,request,apply,restore,restoreAll,changed,inputFor};return {...options,controller:createSemanticFlipController(options)};};
afterEach(()=>vi.useRealTimers());
it('applies only validated completion and clicking a completed occurrence restores without another request',async()=>{const f=setup();f.controller.click(occurrence('a'));await flush();expect(f.apply).toHaveBeenCalledWith(occurrence('a'),'场合');expect(f.controller.completed()).toEqual([{id:'a',position:occurrence('a').position,word:'occasion',replacement:'场合'}]);expect(JSON.stringify(f.controller.completed())).not.toContain('originalRange');f.controller.click(occurrence('a'));await flush();expect(f.restore).toHaveBeenCalledWith('a',true);expect(f.request).toHaveBeenCalledOnce();expect(f.controller.completed()).toEqual([]);f.controller.dispose();f.budget.dispose();});
it('cancels the oldest of two pending clicks when a third arrives and ignores its late completion',async()=>{const f=setup(),jobs=new Map<string,ReturnType<typeof deferred<ReturnType<typeof result>>>>(),signals=new Map<string,AbortSignal>();f.request.mockImplementation((input:any,s:AbortSignal)=>{const d=deferred<ReturnType<typeof result>>();jobs.set(input.occurrence,d);signals.set(input.occurrence,s);return d.promise;});f.controller.click(occurrence('a'));f.controller.click(occurrence('b'));f.controller.click(occurrence('c'));expect(signals.get('a')!.aborted).toBe(true);jobs.get('a')!.resolve(result());jobs.get('c')!.resolve(result());await flush();expect(f.apply.mock.calls.map(c=>c[0].id)).toEqual(['c']);f.controller.click(occurrence('b'));expect(signals.get('b')!.aborted).toBe(true);f.controller.dispose();f.budget.dispose();});
it.each(['targetLanguage','sourceLanguage','aiEpoch'] as const)('resets %s, restores all source and prevents old-domain application',async field=>{const f=setup(),d=deferred<ReturnType<typeof result>>();f.request.mockReturnValue(d.promise);f.controller.click(occurrence('old'));await f.controller.reset({...domain,[field]:field==='aiEpoch'?'new':'es'});d.resolve(result());await flush();expect(f.apply).not.toHaveBeenCalled();expect(f.restoreAll).toHaveBeenCalledOnce();expect(f.controller.completed()).toEqual([]);f.controller.dispose();f.budget.dispose();});
it('keeps source unchanged for invalid formats and identical simple expressions',async()=>{const f=setup();f.request.mockResolvedValueOnce(result('<b>场合</b>')).mockResolvedValueOnce(result('occasion'));f.controller.click(occurrence('invalid'));await flush();expect(f.apply).not.toHaveBeenCalled();expect(f.controller.status().message).toContain('重试');f.controller.click(occurrence('same'));await flush();expect(f.apply).not.toHaveBeenCalled();expect(f.controller.status().message).toBe('已是简明表达');f.controller.dispose();f.budget.dispose();});
it('does not cancel its own async apply during the geometry restore pause and rebinds offset-only records before ready',async()=>{const f=setup(),geometry=deferred<void>();f.apply.mockImplementation(async()=>{f.controller.setSuspended(true);await geometry.promise;f.controller.setSuspended(false);});f.controller.click(occurrence('a'));await flush();const bind=vi.fn(async()=>{});await f.controller.rebind(bind);expect(bind).toHaveBeenCalledWith({id:'a',position:occurrence('a').position,word:'occasion',replacement:'场合'});geometry.resolve();await flush();expect(f.controller.status().lastChange).toEqual({original:'occasion',replacement:'场合'});f.controller.dispose();f.budget.dispose();});
it('suspends fetches, but preserves completed occurrences for explicit restore rebind',async()=>{const f=setup();f.controller.click(occurrence('complete'));await flush();let signal!:AbortSignal;const d=deferred<ReturnType<typeof result>>();f.request.mockImplementation((_input:any,s:AbortSignal)=>{signal=s;return d.promise;});f.controller.click(occurrence('pending'));f.controller.setSuspended(true);expect(signal.aborted).toBe(true);d.resolve(result());await flush();expect(f.controller.completed()).toHaveLength(1);f.controller.setSuspended(false);f.controller.escape();await flush();expect(f.restore).toHaveBeenCalledWith('complete');f.controller.dispose();f.budget.dispose();});
it('rolls back an application that fails geometry rather than retaining a false completed flip',async()=>{const f=setup();f.apply.mockRejectedValue(new Error('geometry failed'));f.controller.click(occurrence('bad'));await flush();expect(f.controller.completed()).toEqual([]);expect(f.restore).toHaveBeenCalledWith('bad');expect(f.controller.status().message).toContain('重试');f.controller.dispose();f.budget.dispose();});
it('caps completed records at 256, evicts and restores the oldest nonvisible item, and refuses when every record is visible',async()=>{const f=setup();let allVisible=false;const c=createSemanticFlipController({...f,isVisible:()=>allVisible});for(let i=0;i<256;i++){c.click(occurrence('w'+i));await flush();}expect(c.completed()).toHaveLength(256);c.click(occurrence('next'));await flush();expect(f.restore).toHaveBeenCalledWith('w0');expect(c.completed()).toHaveLength(256);allVisible=true;const calls=f.request.mock.calls.length;c.click(occurrence('blocked'));await flush();expect(f.request).toHaveBeenCalledTimes(calls);expect(c.status().message).toContain('已达');c.dispose();f.controller.dispose();f.budget.dispose();});
it('owns immediate pending feedback and always clears it on cancellation, errors and disposal',async()=>{
 const f=setup(),d=deferred<ReturnType<typeof result>>(),cleanup=vi.fn(),pending=vi.fn(()=>cleanup);
 const c=createSemanticFlipController({...f,pending,request:async()=>d.promise});
 c.click(occurrence('a'));expect(pending).toHaveBeenCalledWith(occurrence('a'));c.click(occurrence('a'));expect(cleanup).toHaveBeenCalledTimes(1);
 c.click(occurrence('b'));c.dispose();expect(cleanup).toHaveBeenCalledTimes(2);d.resolve(result());await flush();expect(f.apply).not.toHaveBeenCalled();f.controller.dispose();f.budget.dispose();
});
it('skips visual motion feedback for keyboard actions',async()=>{
 const f=setup(),pending=vi.fn(()=>()=>{}),c=createSemanticFlipController({...f,pending});
 c.click(occurrence('a'),{animate:false});await flush();expect(pending).not.toHaveBeenCalled();c.dispose();f.controller.dispose();f.budget.dispose();
});

it('clears waiting feedback on a rejected AI response without creating a replacement',async()=>{const f=setup(),clear=vi.fn(),c=createSemanticFlipController({...f,pending:()=>clear,request:async()=>{throw Error('provider');}});c.click(occurrence('failed'));await flush();expect(clear).toHaveBeenCalledTimes(1);expect(c.completed()).toEqual([]);c.dispose();f.controller.dispose();f.budget.dispose();});
