/** Executed in Playwright CLI's isolated page, using only synthetic loopback documents. */
export async function runReaderModesQA(page){
 const base='http://127.0.0.1:3018',assert=(ok,message)=>{if(!ok)throw new Error(message);};const baseline=await(await page.request.get(base+'/__qa_stats')).json();
 let readyCalls=0;const ready=async()=>{const checkpoint=++readyCalls;try{await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready',{},{timeout:10000});}catch{throw new Error('Reading checkpoint '+checkpoint+' failed: '+JSON.stringify(await page.evaluate(()=>({range:qa.locationRange(),saved:qa.savedProgress(),frames:Array.from(document.querySelectorAll('iframe')).map(f=>({chapter:f.contentDocument?.body?.dataset.chapter,rect:f.getBoundingClientRect().toJSON()})),alerts:Array.from(document.querySelectorAll('[role=alert]')).map(e=>e.textContent)}))));}};
 const tools=async()=>{await page.mouse.move(600,400);await page.mouse.move(600,2);await page.waitForTimeout(50);};
 await page.request.post(base+'/__qa_reset');await page.goto(base+'/?lang=en');await page.evaluate(()=>localStorage.clear());await page.reload();await ready();await tools();
 await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).check();
 let identity=await page.evaluate(()=>qa.cfiIdentity());assert(identity.rendition&&identity.contents,'Wrong actual CFI constructor');
 let calls=await page.evaluate(()=>qa.probeCanonicalCalls());assert(calls.mapping>=2&&calls.selection===1,'Actual Mapping/Contents bypassed the scoped adapter');
 const cfis=await page.evaluate(()=>({first:qa.canonicalWordCFI('CAT',0),second:qa.canonicalWordCFI('CAT',1)}));
 await page.evaluate(cfi=>qa.flipWord(cfi),cfis.first);
 assert(await page.evaluate(()=>qa.completed().length)===1,'No completed flip');assert(await page.evaluate(()=>qa.canonicalWordCFI('CAT',1))===cfis.second,'Second duplicate CFI drifted');
 let body=await page.frames()[1].locator('#duplicates').textContent();assert(body.startsWith('CAT after CAT.')&&await page.frames()[1].locator('[data-semantic-replacement]').getAttribute('data-semantic-replacement')==='a feline animal','Wrong occurrence visually replaced');
 await page.evaluate(cfi=>qa.selectOriginal(cfi),cfis.first);
 const originalCopy=await page.evaluate(()=>{const doc=document.querySelector('iframe').contentDocument;let value;const e=new Event('copy',{cancelable:true,bubbles:true});Object.defineProperty(e,'clipboardData',{value:{setData:(_type,text)=>value=text}});doc.dispatchEvent(e);return {value,prevented:e.defaultPrevented};});assert(originalCopy.value==='CAT'&&originalCopy.prevented,'Copy lost canonical source');
 await page.frames()[1].locator('#duplicates').press('Alt+Enter');await ready();assert(await page.evaluate(()=>qa.completed().length)===0,'Full multiword replacement did not restore');
 await page.evaluate(cfi=>qa.flipWord(cfi),cfis.second);await page.frames()[1].locator('body').press('Escape');await ready();assert(await page.evaluate(()=>qa.completed().length)===0,'Escape did not restore');
 await tools();await page.getByRole('checkbox',{name:'意群阅读',exact:true}).check();
 const positions=new Set();for(let i=0;i<10;i++){positions.add(await page.evaluate(()=>qa.savedProgress()?.location));await tools();await page.getByRole('button',{name:'下一页',exact:true}).click();await page.waitForTimeout(150);}
 assert(positions.size>=8,'Ten screens failed to advance');assert(await page.evaluate(()=>qa.visibleUnits().length)>0,'Missing current visible units');
 await page.evaluate(cfi=>qa.jump(cfi),cfis.second);await ready();assert(await page.evaluate(()=>qa.canonicalWordCFI('CAT',1))===cfis.second,'Saved canonical return drifted');
 for(const theme of ['dark','sepia','light']){await page.evaluate(theme=>qa.setTheme(theme),theme);await page.waitForTimeout(50);assert(await page.evaluate(()=>qa.visibleUnits().length)>0,'Theme broke source geometry');}
 await tools();await page.getByLabel('阅读方式').selectOption('vertical');await ready();assert(await page.evaluate(()=>qa.geometry().axis)==='vertical','Vertical mode uses wrong axis');
 const before=await page.evaluate(()=>qa.savedProgress().location);await page.mouse.move(650,400);await page.mouse.wheel(0,650);await page.waitForTimeout(350);assert(await page.evaluate(()=>qa.savedProgress().location)!==before,'Native vertical wheel did not advance');
 const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});
 const touchBefore=await page.evaluate(()=>qa.savedProgress().location);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:700,y:600}]});for(let y=580;y>=240;y-=40){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:700,y}]});await page.waitForTimeout(20);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(500);assert(await page.evaluate(()=>qa.savedProgress().location)!==touchBefore,'Native touch scrolling was prevented');await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:false});await cdp.detach();
 await tools();await page.getByLabel('阅读方式').selectOption('paginated');await ready();await page.evaluate(cfi=>qa.jump(cfi),cfis.second);await ready();calls=await page.evaluate(()=>qa.probeCanonicalCalls());assert(calls.mapping>=2&&calls.selection===1,'Rebuilt mapping lost adapter');
 // Actual table-of-contents navigation reaches all three synthetic chapters.
 for(const chapter of [2,3]){await tools();await page.getByRole('button',{name:'打开目录与书签',exact:true}).click();await page.getByRole('button',{name:'qa-chapter-'+chapter,exact:true}).click();await page.waitForFunction(n=>qa.savedProgress()?.location?.startsWith('epubcfi(/6/'+(n*2)+'!')&&document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready',chapter,{timeout:10000});await ready();assert(await page.evaluate(n=>qa.loadedChapterIds().includes('qa-chapter-'+n),chapter),'Chapter was not loaded');}
 const tailCFI=await page.evaluate(()=>qa.canonicalWordCFI('TAIL',0,'qa-chapter-3'));await page.evaluate(cfi=>qa.jump(cfi),tailCFI);await ready();await page.waitForTimeout(1200);assert(await page.evaluate(()=>qa.visibleUnits().some(u=>u.key.includes('FINAL TAIL'))),'Long paragraph tail is not measurable');
 await tools();await page.getByRole('checkbox',{name:'意群阅读',exact:true}).uncheck();await page.evaluate(cfi=>qa.jump(cfi),cfis.second);await ready();
 for(const language of ['en','es']){
  await page.goto(base+'/?lang='+language);await page.evaluate(()=>localStorage.clear());await page.reload();await ready();await tools();await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).check();
  for(const target of ['en','zh','es']){
   await tools();await page.getByLabel('翻牌语言').selectOption(target);await page.waitForTimeout(150);await ready();
   const wordCFI=await page.evaluate(word=>qa.canonicalWordCFI(word,0),language==='en'?'CAT':'gato');await page.evaluate(cfi=>qa.flipWord(cfi),wordCFI);assert(await page.evaluate(()=>qa.completed().length)===1,'Language pair did not flip: '+language+'→'+target);
   assert(await page.locator('.sr-only [lang='+target+']').count()>0,'Target language announcement missing');await page.evaluate(cfi=>qa.flipWord(cfi),wordCFI);await ready();assert(await page.evaluate(()=>qa.completed().length)===0,'Language pair failed restore');
  }
 }
 // PDF uses one projection per original prose button, not analysis-control wrappers.
 await page.goto(base+'/?kind=pdf&lang=en');await page.evaluate(()=>localStorage.clear());await page.reload();await ready();await tools();await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).check();
 const button=page.locator('[data-pdf-selection-key]').first(),original=await button.textContent();
 const point=await button.evaluate(el=>{const n=el.querySelector('span').firstChild,r=document.createRange();r.setStart(n,0);r.setEnd(n,9);const rect=r.getBoundingClientRect();return {x:rect.left+rect.width/2,y:rect.top+rect.height/2};});await page.mouse.click(point.x,point.y);await page.waitForSelector('[data-semantic-replacement]',{state:'attached'});assert(await button.textContent()===original,'PDF source reflowed');
 await button.press('Escape');await page.waitForSelector('[data-semantic-replacement]',{state:'detached'});
 await tools();await page.getByRole('checkbox',{name:'意群阅读',exact:true}).check();await page.waitForTimeout(400);await page.emulateMedia({reducedMotion:'reduce'});assert(await button.isVisible(),'Reduced motion broke reading');

 const stats=await (await page.request.get(base+'/__qa_stats')).json();assert(stats.maxActive<=2,'Shared requests exceeded two');assert(stats.dictionary===baseline.dictionary&&stats.explain===baseline.explain&&stats.reading===baseline.reading,'Flip launched legacy analysis');assert(stats.invalid===0,'Invalid synthetic request');
 return {identity,calls,screens:positions.size,flips:stats.flips.length-baseline.flips.length,meaningRequests:stats.meaning.length-baseline.meaning.length,maxActive:stats.maxActive};
}

export async function runReaderGrowthQA(page){
 const base='http://127.0.0.1:3018';await page.request.post(base+'/__qa_reset');await page.goto(base+'/?lang=en');await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).check();const before=await page.evaluate(()=>qa.metrics()[0]);const saved=await page.evaluate(()=>qa.canonicalWordCFI('CAT',1));
 for(let i=0;i<24;i++){await page.request.post(base+'/__qa_fault',{data:{fault:'long'}});await page.evaluate(async i=>{await qa.flipWord(qa.canonicalWordCFI('She',i));},i);}
 const grown=await page.evaluate(()=>qa.metrics()[0]);if(grown.width!==before.width||grown.height!==before.height)throw new Error('Stable flips changed real pagination geometry');if(await page.evaluate(()=>qa.canonicalWordCFI('CAT',1))!==saved)throw new Error('Growth shifted canonical CFI');
 await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).uncheck();await page.waitForFunction(width=>qa.metrics()[0].width===width,before.width,{timeout:10000});await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');const shrunk=await page.evaluate(()=>qa.metrics()[0]);if(shrunk.width!==before.width)throw new Error('Restore did not shrink pagination columns '+JSON.stringify({before,grown,shrunk}));
 await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).check();await page.evaluate(cfi=>qa.jump(cfi),saved);return {before,grown,shrunk,canonical:saved};
}

export async function runReaderTailQA(page){
 const base='http://127.0.0.1:3018';await page.request.post(base+'/__qa_reset');await page.goto(base+'/?lang=en');await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).check();await page.getByRole('button',{name:'打开目录与书签',exact:true}).click();await page.getByRole('button',{name:'qa-chapter-3',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');await page.evaluate(async()=>{await qa.jump(qa.canonicalWordCFI('TAIL',0,'qa-chapter-3'));});await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByRole('checkbox',{name:'意群阅读',exact:true}).check();
 for(let i=0;i<30;i++){await page.waitForTimeout(300);const retry=page.getByRole('button',{name:'重试意群',exact:true});if(await retry.isVisible()){await page.mouse.move(600,400);await page.mouse.move(600,2);await retry.click();}const status=await page.locator('[role=status]').allTextContents();if(status.includes('已标记当前段落'))break;if(i===29)throw new Error('Tail visible processing never completed: '+status);}
 const stats=await (await page.request.get(base+'/__qa_stats')).json();if(!stats.meaning.some(u=>u.text.includes('FINAL TAIL 3.')))throw new Error('Tail unit omitted from AI');const paint=await page.evaluate(()=>{const doc=document.querySelector('iframe').contentDocument;return Array.from(doc.defaultView.CSS.highlights.keys()).filter(k=>k.includes('meaning'));});if(!paint.length)throw new Error('Tail has no CSS highlights');return {tailRequested:true,paint,meaningRequests:stats.meaning.length,maxActive:stats.maxActive};
}

export async function runReaderFaultQA(page){
 const base='http://127.0.0.1:3018',ready=()=>page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');const baseline=await(await page.request.get(base+'/__qa_stats')).json();
 await page.request.post(base+'/__qa_reset');await page.goto(base+'/?lang=en');await page.evaluate(()=>localStorage.clear());await page.reload();await ready();await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).check();
 const cfi=await page.evaluate(()=>qa.canonicalWordCFI('CAT',0));
 for(const fault of ['503','429']){
  await page.request.post(base+'/__qa_fault',{data:{fault}});await page.evaluate(cfi=>qa.flipWord(cfi),cfi);if(await page.evaluate(()=>qa.completed().length)!==0)throw new Error('Fault applied a replacement');
  await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByRole('button',{name:'重试翻牌',exact:true}).click();await page.evaluate(cfi=>qa.flipWord(cfi),cfi);if(await page.evaluate(()=>qa.completed().length)!==1)throw new Error('Explicit retry did not complete');await page.evaluate(cfi=>qa.flipWord(cfi),cfi);await ready();
 }
 const before=(await (await page.request.get(base+'/__qa_stats')).json()).flips.length;
 await page.request.post(base+'/__qa_fault',{data:{fault:'deferred'}});await page.evaluate(cfi=>{void qa.flipWord(cfi).catch(()=>{});},cfi);await page.waitForFunction(()=>Array.from(document.querySelectorAll('[role=status]')).some(e=>e.textContent.includes('理解语境')));await page.frames()[1].locator('body').press('Escape');await page.waitForTimeout(200);
 if(await page.evaluate(()=>qa.completed().length)!==0)throw new Error('Canceled deferred call applied');
 const stats=await (await page.request.get(base+'/__qa_stats')).json();if(stats.flips.length!==before+1||stats.dictionary!==baseline.dictionary||stats.explain!==baseline.explain||stats.reading!==baseline.reading)throw new Error('Fault caused a hidden/repeated legacy request');return {faults:['503','429','deferred'],maxActive:stats.maxActive};
}

export async function runReaderUnsupportedQA(page){
 const base='http://127.0.0.1:3018';await page.request.post(base+'/__qa_reset');await page.goto(base+'/?fixed=1');await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');await page.mouse.move(600,400);await page.mouse.move(600,2);await page.waitForTimeout(150);
 if(await page.getByLabel('阅读方式',{exact:true}).count()||await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).count())throw new Error('Fixed-layout EPUB exposes unsupported flows/flips');
 await page.goto(base+'/?kind=pdf');await page.evaluate(()=>localStorage.clear());await page.reload();await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByLabel('阅读排版').selectOption('original');await page.waitForTimeout(300);
 if(await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).count())throw new Error('PDF original view exposes unsupported flips');return {fixedLayout:'no unsupported controls',pdfOriginal:'no flip control'};
}

export async function runReaderLifecycleQA(page){
 const base='http://127.0.0.1:3018';await page.request.post(base+'/__qa_reset');await page.goto(base+'/?lang=en');await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');
 const mid=await page.evaluate(()=>qa.canonicalWordCFI('She',40));await page.evaluate(cfi=>qa.jump(cfi),mid);await page.waitForFunction(()=>qa.savedProgress()?.percentage>0,{},{timeout:10000});const before=await page.evaluate(()=>qa.savedProgress());if(before.percentage<=0)throw new Error('Lifecycle test has not left the book start');const writeCheckpoint=(await(await page.request.get(base+'/__qa_stats')).json()).writes.length;
 await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).check();await page.evaluate(cfi=>qa.flipWord(cfi),mid);await page.evaluate(()=>qa.store.getState().setTypography(28,2.2));await page.waitForTimeout(300);await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');
 if(await page.evaluate(()=>qa.canonicalWordCFI('She',40))!==mid)throw new Error('Typography changed source CFI');await page.setViewportSize({width:960,height:760});await page.waitForTimeout(400);await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');if(await page.evaluate(()=>qa.savedProgress().percentage)<=0)throw new Error('Resize overwrote progress with the book start');
 await page.mouse.move(500,400);await page.mouse.move(500,2);await page.getByRole('button',{name:'添加书签',exact:true}).click();const entry=await (await page.request.get(base+'/api/documents/fixture-epub-en/reading')).json();if(!entry.items.some(e=>e.kind==='bookmark'&&e.location.startsWith('epubcfi(')))throw new Error('Bookmark lost canonical source position');await page.getByRole('button',{name:'Close bookmarks',exact:true}).click();
 await page.mouse.move(500,400);await page.mouse.move(500,2);await page.getByLabel('阅读方式').selectOption('vertical');await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));await page.waitForTimeout(500);await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');
 await page.mouse.move(500,400);await page.mouse.move(500,2);await page.getByRole('button',{name:'打开目录与书签',exact:true}).click();await page.getByRole('button',{name:/Bookmark 1/}).click();await page.waitForTimeout(200);await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');if(await page.evaluate(()=>qa.savedProgress().percentage)<=0)throw new Error('Bookmark jump returned to book start');
 await page.mouse.move(500,400);await page.mouse.move(500,2);await page.waitForFunction(()=>document.querySelector('[data-reader-toolbar]').dataset.readerToolbar==='visible');await page.mouse.move(600,450);await page.waitForFunction(()=>document.querySelector('[data-reader-toolbar]').dataset.readerToolbar==='hidden');
 const stats=await (await page.request.get(base+'/__qa_stats')).json();if(stats.writes.slice(writeCheckpoint).some(e=>e.location&&e.percentage===0))throw new Error('Pagehide saved a temporary book-start position');await page.setViewportSize({width:1280,height:720});return {canonical:mid,bookmark:entry.items[0].location,pagehide:'no temporary start saved',toolbar:'hover reveal and leave hide'};
}
export async function runReaderFixtureIsolationQA(page){
 const base='http://127.0.0.1:3018';await page.request.post(base+'/__qa_reset');await page.request.patch(base+'/api/documents/fixture-pdf-en/reading',{data:{location:'pdf:fixture-pdf-en:p0',percentage:33}});const epub=await(await page.request.get(base+'/api/documents/fixture-epub-en/reading')).json();if(epub.progress?.location?.startsWith('pdf:'))throw new Error('Synthetic PDF progress leaked into EPUB');return {perDocument:true};
}
export async function runReaderLegacyQA(page){
 const base='http://127.0.0.1:3018';await page.goto(base+'/?lang=en');await page.evaluate(()=>localStorage.clear());await page.request.post(base+'/__qa_reset');await page.reload();const ready=()=>page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');await ready();await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByLabel('阅读方式').selectOption('vertical');await ready();
 const cfi=await page.evaluate(()=>qa.canonicalWordCFI('She',0));await page.evaluate(cfi=>qa.jump(cfi),cfi);await ready();
 const clickWord=async()=>{await page.mouse.move(650,400);await page.waitForTimeout(300);const point=await page.frames()[1].evaluate(()=>{const n=document.querySelector('#p0').firstChild,r=document.createRange(),at=n.textContent.indexOf('She',n.textContent.indexOf('She')+3);r.setStart(n,at);r.setEnd(n,at+3);const p=r.getBoundingClientRect(),f=window.frameElement.getBoundingClientRect();return {x:f.left+p.left+p.width/2,y:f.top+p.top+p.height/2};});await page.mouse.click(point.x,point.y);await page.waitForSelector('[data-study-panel]');};
 await clickWord();await page.mouse.move(650,400);await page.mouse.wheel(0,690);await page.waitForSelector('[data-study-panel]',{state:'detached'});
 await page.evaluate(cfi=>qa.jump(cfi),cfi);await ready();await clickWord();await page.getByRole('button',{name:'固定浮窗',exact:true}).click();const clear=await page.evaluate(()=>{const body=qa.geometry().visible,panel=document.querySelector('[data-study-panel]').getBoundingClientRect();return {x:body.right-panel.right>panel.left-body.left?(panel.right+body.right)/2:(body.left+panel.left)/2,y:400};});await page.mouse.move(clear.x,clear.y);await page.mouse.wheel(0,1500);await page.waitForSelector('[data-study-panel]');await page.getByRole('button',{name:'返回原文 ↗',exact:true}).click();await ready();if(!await page.locator('[data-study-panel]').isVisible())throw new Error('Pinned panel disappeared');await page.getByRole('button',{name:'取消固定',exact:true}).click();await page.getByRole('button',{name:'关闭学习面板',exact:true}).click();
 await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByRole('button',{name:'笔记与 AI 阅读',exact:true}).click();await page.getByLabel('我的笔记').fill('Synthetic original-position note');await page.getByRole('button',{name:'保存划线与笔记',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[aria-label="阅读工具面板"]')?.textContent.includes('Synthetic original-position note'));const saved=await(await page.request.get(base+'/api/documents/fixture-epub-en/reading')).json();const note=saved.items.find(e=>e.kind==='note');if(!note?.location.startsWith('epubcfi(')||note.text!=='She')throw new Error('Note did not preserve source word/CFI');await page.getByRole('button',{name:'回原文',exact:true}).click();await ready();return {float:'scroll close / pinned return',note:{text:note.text,location:note.location}};
}

export async function runReaderCoverQA(page){

const base='http://127.0.0.1:3018',results=[];
for(const url of ['/?cover=1','/?fixed=1&cover=1']){await page.goto(base+url);await page.evaluate(()=>localStorage.clear());await page.request.post(base+'/__qa_reset');await page.reload();try{await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready',{},{timeout:10000});}catch{throw new Error('Cover not ready '+url+' '+JSON.stringify(await page.evaluate(()=>({phase:document.querySelector('[data-reading-phase]')?.dataset.readingPhase,alerts:[...document.querySelectorAll('[role=alert]')].map(x=>x.textContent),range:qa.locationRange(),saved:qa.savedProgress()}))));}results.push({url,progress:await page.evaluate(()=>qa.savedProgress())});await page.mouse.move(600,400);await page.mouse.move(600,2);await page.waitForTimeout(80);await page.getByRole('button',{name:'打开目录与书签',exact:true}).click();await page.getByRole('button',{name:'qa-chapter-2',exact:true}).click();await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready'&&qa.savedProgress()?.location.startsWith('epubcfi(/6/6!'),{},{timeout:10000});}
return results;
}

export async function runReaderDragQA(page){

const base='http://127.0.0.1:3018';await page.request.post(base+'/__qa_reset');await page.goto(base+'/?lang=en');await page.evaluate(()=>localStorage.clear());await page.reload();await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');await page.mouse.move(600,400);await page.mouse.move(600,2);await page.waitForTimeout(70);await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).check();await page.waitForTimeout(250);const before=(await(await page.request.get(base+'/__qa_stats')).json()).flips.length;
const points=await page.evaluate(()=>{const document=window.document.querySelector('iframe').contentDocument;const n=document.querySelector('#duplicates').firstChild,r=document.createRange();r.setStart(n,0);r.setEnd(n,3);const a=r.getBoundingClientRect();r.setStart(n,4);r.setEnd(n,9);const b=r.getBoundingClientRect(),f=window.document.querySelector('iframe').getBoundingClientRect();return {x1:f.left+a.left+1,y1:f.top+a.top+a.height/2,x2:f.left+b.right-1,y2:f.top+b.top+b.height/2};});await page.mouse.move(points.x1,points.y1);await page.mouse.down();await Promise.race([page.mouse.move(points.x2,points.y2),page.waitForTimeout(300)]);await page.mouse.up();await page.waitForTimeout(500);const selection=await page.evaluate(()=>document.querySelector('iframe').contentWindow.getSelection().toString());if(!selection.includes('CAT after'))throw new Error('Real drag failed to select the phrase: '+selection);const after=(await(await page.request.get(base+'/__qa_stats')).json()).flips.length;if(after!==before)throw new Error('Drag-selection initiated paid flip: '+JSON.stringify({selection,before,after}));return {selection,before,after};
}

export async function runReaderNativeReturnQA(page){

const base='http://127.0.0.1:3018',results=[];
for(const flow of ['paginated','vertical']){
await page.goto(base+'/?lang=en&case=native-'+flow);await page.evaluate(()=>localStorage.clear());await page.request.post(base+'/__qa_reset');await page.reload();const ready=()=>page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready',{},{timeout:10000});await ready();const tools=async()=>{await page.mouse.move(600,400);await page.mouse.move(600,2);await page.waitForTimeout(80);};await tools();if(flow==='vertical'){await page.getByLabel('阅读方式').selectOption(flow);await ready();await tools();}await page.getByRole('checkbox',{name:'语义翻牌',exact:true}).check();if(!await page.evaluate(()=>qa.savedProgress()?.location.startsWith('epubcfi(/6/2!')))throw new Error('Native test did not start in chapter 1');const cfi=await page.evaluate(()=>qa.canonicalWordCFI('CAT',0));await page.evaluate(cfi=>qa.flipWord(cfi),cfi);await ready();await page.evaluate(()=>{window.nativeOldFrame=document.querySelector('iframe');window.nativeOldDoc=window.nativeOldFrame.contentDocument;});const start=(await(await page.request.get(base+'/__qa_stats')).json()).flips.length;
let forward=0;for(;forward<80;forward++){await tools();await page.getByRole('button',{name:flow==='vertical'?'下一屏':'下一页',exact:true}).click();await page.waitForTimeout(150);if(await page.evaluate(()=>!window.nativeOldFrame.isConnected))break;}if(forward===80)throw new Error('Native navigation did not evict old document '+flow);
let back=0;for(;back<80;back++){await tools();await page.getByRole('button',{name:flow==='vertical'?'上一屏':'上一页',exact:true}).click();await page.waitForTimeout(150);if(await page.evaluate(()=>[...document.querySelectorAll('iframe')].some(f=>f.contentDocument!==window.nativeOldDoc&&f.contentDocument?.body?.dataset.chapter==='qa-chapter-1'&&qa.savedProgress()?.location.startsWith('epubcfi(/6/2!'))))break;}if(back===80)throw new Error('Native navigation did not recreate chapter '+flow);await ready();const text=await page.evaluate(()=>[...document.querySelectorAll('iframe')].find(f=>f.contentDocument?.body?.dataset.chapter==='qa-chapter-1').contentDocument.querySelector('[data-semantic-replacement]')?.dataset.semanticReplacement??'');if(text!=='a feline animal')throw new Error('Completed flip lost after native return '+flow+': '+text);const end=(await(await page.request.get(base+'/__qa_stats')).json()).flips.length;if(end!==start)throw new Error('Native rebind called provider');results.push({flow,forward:forward+1,back:back+1,evicted:true,recreated:true,retained:true,providerDelta:end-start});}
return results;
}

export async function runReaderMotionQA(page,outputDir){
 await page.unrouteAll({behavior:'ignoreErrors'});await page.emulateMedia({reducedMotion:'no-preference'});
 const base='http://127.0.0.1:3018',assert=(v,m)=>{if(!v)throw Error(m);};
 await page.setViewportSize({width:1400,height:900});await page.request.post(base+'/__qa_reset');await page.goto(base+'/?case=animation');await page.evaluate(()=>localStorage.clear());await page.reload();
 await page.waitForFunction(()=>document.querySelector('[data-reading-phase]')?.dataset.readingPhase==='ready');await page.mouse.move(600,400);await page.mouse.move(600,2);await page.getByLabel('语义翻牌',{exact:true}).check();await page.mouse.move(1390,700);await page.waitForTimeout(350);
 const point=()=>page.evaluate(()=>{const f=document.querySelector('iframe'),d=f.contentDocument,p=d.querySelector('#duplicates'),r=d.createRange();r.setStart(p.firstChild,0);r.setEnd(p.firstChild,3);const a=r.getBoundingClientRect(),fr=f.getBoundingClientRect();return {x:fr.left+a.left+a.width/2,y:fr.top+a.top+a.height/2};});
 const metrics=()=>page.evaluate(()=>({view:qa.metrics(),progress:qa.savedProgress(),text:document.querySelector('iframe').contentDocument.querySelector('#duplicates').textContent,rect:[...document.querySelector('iframe').contentDocument.querySelectorAll('p')].map(e=>{const r=e.getBoundingClientRect();return [r.x,r.y,r.width,r.height]})}));
 let release;let mode='ok';const gate=new Promise(r=>release=r);
 await page.route('**/api/semantic-flip',async route=>{await gate;if(mode==='fail')return route.fulfill({status:503,body:'{}'});return route.fulfill({status:200,contentType:'application/x-ndjson',body:JSON.stringify({type:'start',requestId:'motion',cached:false})+'\n'+JSON.stringify({type:'complete',requestId:'motion',value:{replacement:'a feline animal',provider:'synthetic',model:'fixture'}})+'\n'});});
 const before=await metrics(),pt=await point();await page.mouse.click(pt.x,pt.y);
 await page.waitForFunction(()=>document.querySelector('iframe').contentDocument.querySelector('[data-semantic-state=pending]'));
 const pending=await page.evaluate(()=>{const f=document.querySelector('iframe'),s=f.contentDocument.querySelector('[data-semantic-state=pending] [data-semantic-slot]');return {animation:f.contentWindow.getComputedStyle(s).animationName,transform:f.contentWindow.getComputedStyle(s).transform,source:f.contentDocument.querySelector('#duplicates').textContent}});
 assert(pending.animation==='reader-word-wait'&&pending.transform!=='none','Pending motion not active '+JSON.stringify(pending));assert(JSON.stringify(await metrics())===JSON.stringify(before),'Waiting moved original layout');
 await page.waitForTimeout(500);if(outputDir)await page.screenshot({path:outputDir+'/animation-wait.png'});release();await page.waitForFunction(()=>qa.completed().length===1);
 const complete=await page.evaluate(()=>{const f=document.querySelector('iframe'),s=f.contentDocument.querySelector('[data-semantic-replacement] [data-semantic-slot]');return f.contentWindow.getComputedStyle(s).animationName;});assert(complete==='reader-word-turn','Completion is not 3D turn');assert(JSON.stringify(await metrics())===JSON.stringify(before),'Completion moved original layout');
 await page.waitForTimeout(200);await page.mouse.move(1390,700);await page.mouse.move(pt.x,pt.y);if(outputDir)await page.screenshot({path:outputDir+'/animation-done.png'});await page.mouse.click(pt.x,pt.y);await page.waitForFunction(()=>qa.completed().length===0);assert(await page.evaluate(()=>!!document.querySelector('iframe').contentDocument.querySelector('[data-semantic-state=restore]')),'Reverse motion absent');await page.waitForTimeout(180);assert(await page.evaluate(()=>!document.querySelector('iframe').contentDocument.querySelector('[data-semantic-state=restore]')),'Reverse presentation leaked');
 await page.emulateMedia({reducedMotion:'reduce'});await page.mouse.click(pt.x,pt.y);await page.waitForFunction(()=>qa.completed().length===1);
 assert(await page.evaluate(()=>{const f=document.querySelector('iframe'),s=f.contentDocument.querySelector('[data-semantic-slot]'),c=f.contentWindow.getComputedStyle(s);return c.animationName==='none'&&c.transform==='none'}),'Reduced motion still rotates');
 await page.mouse.click(pt.x,pt.y);await page.waitForFunction(()=>qa.completed().length===0);await page.waitForTimeout(180);mode='fail';await page.mouse.click(pt.x,pt.y);await page.waitForTimeout(250);assert(await page.evaluate(()=>!document.querySelector('iframe').contentDocument.querySelector('[data-semantic-pending]')&&qa.completed().length===0),'Failed call left waiting overlay');
 await page.unroute('**/api/semantic-flip');await page.emulateMedia({reducedMotion:'no-preference'});
 return {pending,complete,stableGeometry:true,reverse:true,reducedMotion:true,failureCleanup:true};
}
